"""Financial_Market_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15Hf0VVR8zjci1M9G2UVC0-d1hmGthiYQ

# **Financial Market News - Sentiment Analysis**

-------------

## **Objective**

## **Data Source**

## **Import Library**
"""

import pandas as pd
import numpy as np

"""## **Import Data**"""

df= pd.read_csv(r'https://raw.githubusercontent.com/YBI-Foundation/Dataset/main/Financial%20Market%20News.csv',encoding="ISO-8859-1")

"""## **Describe Data**"""

df.head()

"""## **Data Visualization**"""

df.info()

df.shape

df.columns

"""## **Data Preprocessing**"""

' '.join(str(x) for x in df.iloc[1,2:27])

df.index

len(df.index)

news=[]
for row in range(0,len(df.index)):
  news.append(' '.join(str(x) for x in df.iloc[row,2:27]))

type(news)

news[0]

"""## **Define Target Variable (y) and Feature Variables (X)**"""

x=news

type(x)

from sklearn.feature_extraction.text import CountVectorizer

cv=CountVectorizer(lowercase= True,ngram_range=(1,1))

x=cv.fit_transform(x)

x.shape

y=df['Label']

y.shape

"""## **Train Test Split**"""

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(x,y,test_size=0.3,stratify=y,random_state=2529)

"""## **Modeling**"""

from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=200)
rf.fit(X_train,y_train)

"""## **Prediction**"""

y_pred=rf.predict(X_test)

"""## **Model Evaluation**"""

from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

confusion_matrix(y_test,y_pred)

print(classification_report(y_test,y_pred))

"""## **Explaination**"""
